file_panel_border = "#b5a0fe"
sidebar_border = "#9375f5"
footer_border = "#dcd2fe"

file_panel_border_active = "#b5a0fe"
sidebar_border_active = "#9375f5"
footer_border_active = "#dcd2fe"
modal_border_active = "#a0c4ff"

full_screen_bg = "#00000000"
file_panel_bg = "#00000000"
sidebar_bg = "#00000000"
footer_bg = "#00000000"
modal_bg = "#00000000"

full_screen_fg = "#efebff"
file_panel_fg = "#efebff"
sidebar_fg = "#efebff"
footer_fg = "#efebff"
modal_fg = "#efebff"

cursor = "#ffadad"
correct = "#ffadad"
error = "#ffadad"
hint = "#ffadad"
cancel = "#ffadad"

file_panel_top_directory_icon = "#d294ff"
file_panel_top_path = "#d294ff"
file_panel_item_selected_fg = "#d294ff"
file_panel_item_selected_bg = "#d294ff"

sidebar_title = "#ca80ff"
sidebar_item_selected_fg = "#ca80ff"
sidebar_item_selected_bg = "#00000000"
sidebar_divider = "#ca80ff"

modal_cancel_fg = "#9bf6ff"
modal_cancel_bg = "#00000000"

modal_confirm_fg = "#caffbf"
modal_confirm_bg = "#00000000"


help_menu_hotkey = "#ffb86c"
help_menu_title = "#bd93f9"
